
const institutes = [
  {
    name: 'LNCT',
    location: 'Bhopal',
    description: 'Premier engineering and technology institute known for academic excellence and innovation.',
    students: '10,000+',
    established: '1994',
    specialties: ['Engineering', 'Technology', 'Innovation'],
    image: './images/lnct-main-bhopal.jpg',
  },
  {
    name: 'LNCT & Science',
    location: 'Bhopal',
    description: 'Integrated institute offering science and technology programs with a strong research focus.',
    students: '5,000+',
    established: '2001',
    specialties: ['Science', 'Technology', 'Research'],
    image: './images/lncts-bhopal.webp',
  },
  {
    name: 'LNCT Excellence',
    location: 'Bhopal',
    description: 'Dedicated to excellence in engineering and management education with modern infrastructure.',
    students: '7,000+',
    established: '2007',
    specialties: ['Engineering', 'Management'],
    image: './images/lnct-e-bhopal.png',
  },
  {
    name: 'LNCT MCA',
    location: 'Bhopal',
    description: 'Providing quality education in computer applications and software development.',
    students: '1,200+',
    established: '2009',
    specialties: ['Computer Applications', 'Software Development'],
    image: './images/lnct-mca-bhopal.jpg',
  },
  {
    name: 'LNCT University',
    location: 'Bhopal',
    description: 'Premier university offering undergraduate and postgraduate programs in Engineering, Management, and Applied Sciences.',
    students: '15,000+',
    established: '2003',
    specialties: ['Engineering', 'Management', 'Computer Science', 'Research'],
    image: './images/lnct-university-bhopal.jpg',
  },
  {
    name: 'LNCT Pharmacy',
    location: 'Bhopal',
    description: 'Excellence in pharmaceutical education with modern laboratories and research facilities.',
    students: '2,000+',
    established: '2001',
    specialties: ['Pharmaceutical Sciences', 'Drug Research', 'Clinical Pharmacy'],
    image: './images/lnct-pharmacy-bhopal.webp',
  },
  {
    name: 'JNCT Bhopal',
    location: 'Bhopal',
    description: 'Sister concern of LNCT, known for engineering and polytechnic education.',
    students: '6,000+',
    established: '2010',
    specialties: ['Polytechnic', 'Engineering'],
    image: './images/jnct-bhopal.JPG',
  },
  {
    name: 'LNCT Vidhyapeeth University',
    location: 'Indore',
    description: 'A multidisciplinary university offering UG, PG, and PhD programs.',
    students: '10,000+',
    established: '2021',
    specialties: ['Engineering', 'Pharmacy', 'Sciences', 'Humanities'],
    image: './images/lnct-vidyapeeth-indore.png',
  },
  {
    name: 'Rishiraj College',
    location: 'Bhopal',
    description: 'One of the premier institute of Central India for Dental Education',
    students: '2,500+',
    established: '2005',
    specialties: ['Pharmacy', 'Life Sciences'],
    image: './images/rishiraj-college-bhopal.jpg',
  },
  {
    name: 'LNCT Jabalpur',
    location: 'Jabalpur',
    description: 'LNCT’s extension into Jabalpur for quality engineering and management education.',
    students: '4,000+',
    established: '2018',
    specialties: ['Engineering', 'Management'],
    image: './images/lnct-jabalpur.jpg',
  },
  {
    name: 'CEC Bilaspur',
    location: 'Bilaspur',
    description: 'Central India-based institute under LNCT Group offering engineering and technology courses.',
    students: '3,000+',
    established: '2002',
    specialties: ['Engineering', 'Technology'],
    image: './images/cec-bilaspur.jpeg',
  },
  {
    name: 'LNCT Bhopal Indore Campus',
    location: 'Indore',
    description: 'Extending LNCT’s legacy to Indore with modern education and industry exposure.',
    students: '3,500+',
    established: '2015',
    specialties: ['Engineering', 'Management'],
    image: './images/lnct-bhopal-indore.png',
  },
  {
    name: 'LNCT Indore',
    location: 'Indore',
    description: 'Emerging engineering institution bringing LNCT excellence to Indore.',
    students: '4,000+',
    established: '2017',
    specialties: ['Engineering', 'Technology'],
    image: './images/lnct-indore.webp',
  },
  {
    name: 'LNCTS (RIT) Indore',
    location: 'Indore',
    description: 'Technological institute focusing on research, innovation, and academic rigor.',
    students: '3,000+',
    established: '2016',
    specialties: ['Technology', 'Innovation'],
    image: './images/lncts-indore.avif',
  },
  {
    name: 'LNCP Indore',
    location: 'Indore',
    description: 'Pharmacy-focused institute with industry-linked research labs and practical learning.',
    students: '2,000+',
    established: '2018',
    specialties: ['Pharmacy', 'Healthcare'],
    image: './images/lncp-indore.png',
  },
  {
    name: 'LNCPS Indore',
    location: 'Indore',
    description: 'Specializes in paramedical and clinical sciences with state-of-the-art labs.',
    students: '1,800+',
    established: '2019',
    specialties: ['Clinical Sciences', 'Paramedical'],
    image: './images/lncps-indore.jpg',
  },
  {
    name: 'JDCP Indore',
    location: 'Indore',
    description: 'Dental college with advanced clinical training and patient care facilities.',
    students: '1,200+',
    established: '2020',
    specialties: ['Dentistry', 'Oral Health'],
    image: 'jdcp-indore.webp',
  },
  {
    name: 'JDCN Indore',
    location: 'Indore',
    description: 'Nursing college training future health professionals with practical hospital exposure.',
    students: '900+',
    established: '2021',
    specialties: ['Nursing', 'Healthcare'],
    image: './images/jdcn-indore.jpg',
  },
  {
    name: 'NSHMC Bhopal',
    location: 'Bhopal',
    description: 'Homeopathy medical college offering clinical and research-oriented programs.',
    students: '700+',
    established: '2022',
    specialties: ['Homeopathy', 'Medical Sciences'],
    image: './images/nshmc-bhopal.webp',
  },
  {
    name: 'LNCT Gwalior',
    location: 'Gwalior',
    description: 'To be known as the destination of choice for aspiring engineers.',
    students: '4,000+',
    established: '2009',
    specialties: ['Engineering', 'Technology', 'Pharmacy'],
    image: './images/lnct-gwalior.jpg',
  },
  {
    name: 'LNCTS Gwalior (Diploma)',
    location: 'Gwalior',
    description: 'Diploma institute focusing on skill-based technical education.',
    students: '1,200+',
    established: '2018',
    specialties: ['Diploma', 'Polytechnic'],
    image: './images/lncts-gwalior.webp',
  },
  {
    name: 'LNCM Gwalior',
    location: 'Gwalior',
    description: 'College of management developing future business leaders.',
    students: '1,000+',
    established: '2019',
    specialties: ['Management', 'Finance'],
    image: './images/lncm-gwalior.jpg',
  },
  {
    name: 'SITE Nathdwara',
    location: 'Nathdwara',
    description: 'Technology institute offering engineering and IT courses with industrial interface.',
    students: '2,500+',
    established: '2016',
    specialties: ['IT', 'Engineering'],
    image: './images/site-nathdwara.avif',
  },
  {
    name: 'SIBM Nathdwara',
    location: 'Nathdwara',
    description: 'Business management institute providing corporate-ready programs.',
    students: '1,200+',
    established: '2017',
    specialties: ['Management', 'Business Studies'],
    image: './images/sibm-nathdwara.webp',
  },
  {
    name: 'SIP Nathdwara',
    location: 'Nathdwara',
    description: 'Pharmacy college offering B.Pharm and D.Pharm with research exposure.',
    students: '1,000+',
    established: '2018',
    specialties: ['Pharmacy'],
    image: './images/sip-nathdwara.webp',
  },
  {
    name: 'LNCT World School',
    location: 'Bhopal',
    description: 'CBSE-affiliated K-12 school nurturing young minds with a modern curriculum and global outlook.',
    students: '2,000+',
    established: '2014',
    specialties: ['Primary Education', 'STEM', 'Holistic Learning'],
    image: './images/lnctworldschool-bhopal.webp',
  }
];

export default institutes;